/***************************************************************
* file: Basic.java
* author: Kenneth Chau, Tina Arezoomanians, Kelly Lwin
* class: CS 4450.01 (S25-Regular) Computer Graphics
*
* assignment: Final Program
* date last modified: 05/04/2025
* 
* purpose: The program create an original scene in MineCraft fashion.
* note: The program contains code that is assisted but not generated by AI.
****************************************************************/
package Program1;

import java.io.IOException;
import org.lwjgl.input.Keyboard;
import org.lwjgl.opengl.Display;
import org.lwjgl.opengl.DisplayMode;
import org.lwjgl.opengl.GL11;
import org.lwjgl.util.glu.GLU;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import org.lwjgl.openal.AL;
import org.lwjgl.openal.AL10;
import org.newdawn.slick.openal.Audio;
import org.newdawn.slick.openal.AudioLoader;
import org.newdawn.slick.openal.SoundStore;
import org.newdawn.slick.util.ResourceLoader;

public class Basic {

    // Window constants
    private static final int WINDOW_WIDTH = 640;
    private static final int WINDOW_HEIGHT = 480;
    static final int FRAME_RATE = 60;
    private static final String WINDOW_TITLE = "Final Program";
    
    // Camera instance
    private Camera camera;
    private boolean isDay = true;
    private boolean isHellMode = false;

    // Chicken list
    private List<Chicken> chickens = new ArrayList<>();
    private List<Chicken> vocalChickens = new ArrayList<>();
    
    // key debouncing
    private boolean HPressed = false;
    
    // audio
    private Audio chickenSound;
    private Audio hellModeSound;
    private static final String CHICKEN_SOUND_PATH = "textures/chicken_cluck.wav";
    private static final String HELL_MODE_SOUND_PATH = "textures/hell_mode.wav";
    private float vocalSelectTimer = 0;
    private static final float VOCAL_SELECTION_INTERVAL = 10.0f;
    private static final int MAX_VOCAL_CHICKENS = 3;
    private Random random = new Random();

    // Start the program: create the window, initialize OpenGL, and run the render loop.
    public void start() {
        try {
            createWindow();
            initGL();
            initAudio();
            camera = new Camera(30.0f, 30.0f, 100.0f);
            Skybox.initSkybox(); // Initialize sky box

            // Spawn chickens at random terrain positions
            for (int i = 0; i < 10; i++) {
                float x = (float)(Math.random() * TerrainGenerator.WIDTH) * 2;
                float z = (float)(Math.random() * TerrainGenerator.DEPTH) * 2;
                chickens.add(new Chicken(x, z, chickenSound));
            }
            
            // init vocal chickens
            selectVocalChickens();

            render();
        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        } finally {
            cleanup();
        }
    }

    // Creates an OpenGL window.
    private void createWindow() throws Exception {
        Display.setFullscreen(false);
        Display.setDisplayMode(new DisplayMode(WINDOW_WIDTH, WINDOW_HEIGHT));
        
        // Center the window on the desktop.
        DisplayMode desktop = Display.getDesktopDisplayMode();
        int x = (desktop.getWidth() - WINDOW_WIDTH) / 2;
        int y = (desktop.getHeight() - WINDOW_HEIGHT) / 2;
        Display.setLocation(x, y);

        Display.setTitle(WINDOW_TITLE);
        Display.create();
        
        // Capture the mouse for first-person look control.
        org.lwjgl.input.Mouse.setGrabbed(true);
    }

    // Initializes OpenGL settings.
    private void initGL() {
        // Enable depth testing and textures.
        GL11.glEnable(GL11.GL_DEPTH_TEST);
        GL11.glEnable(GL11.GL_TEXTURE_2D);
        
        // initialize lighting
        Lighting.initLighting();
        
        // Set the clear color to black.
        GL11.glClearColor(0f, 0f, 0f, 1f);

        GL11.glMatrixMode(GL11.GL_PROJECTION);
        GL11.glLoadIdentity();
        GLU.gluPerspective(70.0f, (float) WINDOW_WIDTH / WINDOW_HEIGHT, 0.1f, 1000f);
        GL11.glMatrixMode(GL11.GL_MODELVIEW);
        GL11.glHint(GL11.GL_PERSPECTIVE_CORRECTION_HINT, GL11.GL_NICEST);
    }
    
    // initializes audio resources
    private void initAudio() {
        try {
            SoundStore.get().init();
            // load chicken cluck wav
            chickenSound = AudioLoader.getAudio("WAV", ResourceLoader.getResourceAsStream(CHICKEN_SOUND_PATH));
            if (chickenSound != null) {
                chickenSound.playAsSoundEffect(1.0f, 0.1f, false);
            }
            
            // load hell mode wav
            hellModeSound = AudioLoader.getAudio("WAV", ResourceLoader.getResourceAsStream(HELL_MODE_SOUND_PATH));
        } catch (IOException e) {
            System.err.println("Failed t load chicken sound: " + e.getMessage());
            e.printStackTrace();
            chickenSound = null;
            hellModeSound = null;
        }
    }
    
    // clean up the audio resources
    private void cleanup() {
        if (chickenSound != null) {
            chickenSound.stop();
            chickenSound = null;
        }
        if (hellModeSound != null) {
            hellModeSound.stop();
            hellModeSound = null;
        }
        AL.destroy();
    }
    
    // select random chickens to be vocal (currently set for 3-4)
    private void selectVocalChickens() {
        vocalChickens.clear();
        List<Chicken> tmpList = new ArrayList<>(chickens);
        Collections.shuffle(tmpList, random);
        
        int numVocal = Math.min(MAX_VOCAL_CHICKENS, tmpList.size());
        numVocal = random.nextInt(2) + 3;   // randomly 3 or 4
        
        for (int i = 0; i < numVocal; i++) {
            vocalChickens.add(tmpList.get(i));
            tmpList.get(i).setVocal(true);
        }
        
        // non vocal chickens
        for (Chicken chicken : tmpList.subList(numVocal, tmpList.size())) {
            chicken.setVocal(false);
        }
    }
    
    // This handles user input from the keyboard.
    private void handleInput() {
        if (Keyboard.isKeyDown(Keyboard.KEY_N)) {
            isDay = false;
        } else if (Keyboard.isKeyDown(Keyboard.KEY_M)) {
            isDay = true;
        }
        
        // toggles hell mode on F1
        if (Keyboard.isKeyDown(Keyboard.KEY_H) && !HPressed) {
            isHellMode = !isHellMode;
            HPressed = true;
            if (isHellMode && hellModeSound != null) {
                hellModeSound.playAsSoundEffect(1.0f, 0.3f, false);
            }
        } else if (!Keyboard.isKeyDown(Keyboard.KEY_H)) {
            HPressed = false;
        }
    }

    // The render loop. It now uses your TerrainGenerator to draw the full textured terrain.
    private void render() {
        // Create an instance of your terrain generator.
        TerrainGenerator terrain = new TerrainGenerator();
        
        while (!Display.isCloseRequested() && !Keyboard.isKeyDown(Keyboard.KEY_ESCAPE)) {
            // Handle User Input
            handleInput();
            
            // Update the camera based on user input.
            camera.update();
            
            // update openAL listener position to match camera
            if (chickenSound != null) {
                AL10.alListener3f(AL10.AL_POSITION, camera.x, camera.y, camera.z);
                AL10.alListener3f(AL10.AL_VELOCITY, 0, 0, 0);
            }
            
            // update vocal selection timer
            vocalSelectTimer += 1.0f / FRAME_RATE;
            if (vocalSelectTimer >= VOCAL_SELECTION_INTERVAL) {
                selectVocalChickens();
                vocalSelectTimer = 0;
            }
            
            // Clear the screen and reset the modelview matrix.
            GL11.glClear(GL11.GL_COLOR_BUFFER_BIT | GL11.GL_DEPTH_BUFFER_BIT);
            GL11.glLoadIdentity();
            
            // Apply the camera view transformation.
            camera.applyView();
           
            // Draw the skybox
            Skybox.setDay(isDay);
            Skybox.render(camera.x, camera.y, camera.z, isHellMode);
            
            // update light position after camera transformation
            Lighting.updateLight();
            
            // Draw the terrain (textured cubes generated via noise).
            terrain.drawTerrain(isHellMode);

            // Update and draw all chickens
            for (Chicken chicken : chickens) {
                chicken.update();
                chicken.draw();
            }
            
            SoundStore.get().poll(0);
            
            Display.update();
            Display.sync(FRAME_RATE);
        }
        Display.destroy();
    }

    // Main method.
    public static void main(String[] args) {
        Basic basic = new Basic();
        basic.start();
    }
}
