/***************************************************************
* file: Camera.java
* author: Kenneth Chau, Tina Arezoomanians, Kelly Lwin
* class: CS 4450.01 (S25-Regular) Computer Graphics
*
* assignment: Final Program Checkpoint 1
* date last modified: 3/27/2025
*
* purpose: The program displays a cube in 3D space with each face colored differently
* note: The program contains code that is assisted but not generated by AI.
****************************************************************/

package Program1;

import org.lwjgl.input.Mouse; 
import org.lwjgl.util.vector.Vector3f;

public class Camera {
    // Camera position and orientation. 
    public float x, y, z; 
    public float yaw, pitch;
    
    // Sensitivity and movement speed.
    public float mouseSensitivity = 0.1f;
    public float movementSpeed = 0.1f;

    public Camera(float x, float y, float z) {
        this.x = x;
        this.y = y;
        this.z = z;
        this.yaw = 0;
        this.pitch = 0;
    }

    // Updates the camera orientation based on mouse input and position using the KeyboardHelper.
    public void update() {
        // Update orientation from mouse movement.
        yaw += Mouse.getDX() * mouseSensitivity;
        pitch -= Mouse.getDY() * mouseSensitivity;
        if (pitch > 90)  pitch = 90;
        if (pitch < -90) pitch = -90;

        // Update position based on keyboard input.
        // (KeyboardHelper.getMovementDelta uses the current yaw for horizontal movement.)
        Vector3f delta = PlayerMovement.getMovementDelta(movementSpeed, yaw);
        x += delta.x;
        y += delta.y;
        z += delta.z;
    }

    // Applies the camera transformation to the current OpenGL modelview matrix.
    public void applyView() {
        // Note: Rotations are applied first, then the inverse translation.
        org.lwjgl.opengl.GL11.glRotatef(pitch, 1, 0, 0);
        org.lwjgl.opengl.GL11.glRotatef(yaw, 0, 1, 0);
        org.lwjgl.opengl.GL11.glTranslatef(-x, -y, -z);
    }
}