/***************************************************************
* file: Cube.java
* author: Kenneth Chau, Tina Arezoomanians, Kelly Lwin
* class: CS 4450.01 (S25-Regular) Computer Graphics
*
* assignment: Final Program Checkpoint 1
* date last modified: 3/27/2025
*
* purpose: The program displays a cube in 3D space with each face colored differently
* note: The program contains code that is assisted but not generated by AI.
****************************************************************/

package Program1;

import org.lwjgl.opengl.GL11;

public class Cube {
    // Draws a cube (side length 2) with each face having a unique color.
    public static void drawCube() {
        GL11.glBegin(GL11.GL_QUADS);
        // Front face (red)
        GL11.glColor3f(1, 0, 0);
        GL11.glVertex3f(-1, -1, -1);
        GL11.glVertex3f(1, -1, -1);
        GL11.glVertex3f(1, 1, -1);
        GL11.glVertex3f(-1, 1, -1);

        // Back face (green)
        GL11.glColor3f(0, 1, 0);
        GL11.glVertex3f(-1, -1, 1);
        GL11.glVertex3f(1, -1, 1);
        GL11.glVertex3f(1, 1, 1);
        GL11.glVertex3f(-1, 1, 1);

        // Left face (blue)
        GL11.glColor3f(0, 0, 1);
        GL11.glVertex3f(-1, -1, -1);
        GL11.glVertex3f(-1, 1, -1);
        GL11.glVertex3f(-1, 1, 1);
        GL11.glVertex3f(-1, -1, 1);

        // Right face (yellow)
        GL11.glColor3f(1, 1, 0);
        GL11.glVertex3f(1, -1, -1);
        GL11.glVertex3f(1, 1, -1);
        GL11.glVertex3f(1, 1, 1);
        GL11.glVertex3f(1, -1, 1);

        // Top face (cyan)
        GL11.glColor3f(0, 1, 1);
        GL11.glVertex3f(-1, 1, -1);
        GL11.glVertex3f(1, 1, -1);
        GL11.glVertex3f(1, 1, 1);
        GL11.glVertex3f(-1, 1, 1);

        // Bottom face (magenta)
        GL11.glColor3f(1, 0, 1);
        GL11.glVertex3f(-1, -1, -1);
        GL11.glVertex3f(1, -1, -1);
        GL11.glVertex3f(1, -1, 1);
        GL11.glVertex3f(-1, -1, 1);
        GL11.glEnd();
    }
}