/***************************************************************
* file: PlayerMovement.java
* author: Kenneth Chau, Tina Arezoomanians, Kelly Lwin
* class: CS 4450.01 (S25-Regular) Computer Graphics
*
* assignment: Final Program Checkpoint 1
* date last modified: 3/27/2025
*
* purpose: The program tracks keyboard input and updates player movement.
* note: The program contains code that is assisted but not generated by AI.
****************************************************************/

package Program1;

import org.lwjgl.input.Keyboard;
import org.lwjgl.util.vector.Vector3f;

public class PlayerMovement {

    // method - getMovementDelta  
    // purpose - calculates player movement based on keyboard input and camera yaw  
    public static Vector3f getMovementDelta(float movementSpeed, float cameraYaw) {
        // Convert yaw angle to radians.
        float yawRad = (float) Math.toRadians(cameraYaw);

        // Calculate forward and right directional components.
        float forwardX = (float) Math.sin(yawRad);
        float forwardZ = (float) -Math.cos(yawRad);
        float rightX   = (float) Math.cos(yawRad);
        float rightZ   = (float) Math.sin(yawRad);

        Vector3f delta = new Vector3f(0, 0, 0);

        // Forward movement (W or UP)
        if (Keyboard.isKeyDown(Keyboard.KEY_W) || Keyboard.isKeyDown(Keyboard.KEY_UP)) {
            delta.x += forwardX * movementSpeed;
            delta.z += forwardZ * movementSpeed;
        }
        // Backward movement (S or DOWN)
        if (Keyboard.isKeyDown(Keyboard.KEY_S) || Keyboard.isKeyDown(Keyboard.KEY_DOWN)) {
            delta.x -= forwardX * movementSpeed;
            delta.z -= forwardZ * movementSpeed;
        }
        // Left (A or LEFT)
        if (Keyboard.isKeyDown(Keyboard.KEY_A) || Keyboard.isKeyDown(Keyboard.KEY_LEFT)) {
            delta.x -= rightX * movementSpeed;
            delta.z -= rightZ * movementSpeed;
        }
        // Right (D or RIGHT)
        if (Keyboard.isKeyDown(Keyboard.KEY_D) || Keyboard.isKeyDown(Keyboard.KEY_RIGHT)) {
            delta.x += rightX * movementSpeed;
            delta.z += rightZ * movementSpeed;
        }
        // Upward (SPACE)
        if (Keyboard.isKeyDown(Keyboard.KEY_SPACE)) {
            delta.y += movementSpeed;
        }
        // Downward (LEFT SHIFT)
        if (Keyboard.isKeyDown(Keyboard.KEY_LSHIFT)) {
            delta.y -= movementSpeed;
        }
        return delta;
    }
}
